# Generated by Django 6.0.1 on 2026-01-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_choice_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='annotated_html',
            field=models.TextField(blank=True, help_text='Stores the HTML with highlights/notes'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='content',
            field=models.TextField(blank=True, help_text='Write your notes here...'),
        ),
    ]
