# Generated by Django 6.0.1 on 2026-01-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_category_alter_studentnote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='quiz_release_date',
            field=models.DateTimeField(blank=True, help_text='If set, students cannot take the quiz before this time.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
