# Generated by Django 6.0.1 on 2026-01-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lecture_quiz_release_date_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='quiz_release_date',
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_quiz_unlocked',
            field=models.BooleanField(default=False, verbose_name='Unlock Quiz?'),
        ),
    ]
