# Generated by Django 6.0.1 on 2026-01-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lecture_quiz_release_date_and_more'),
        ('users', '0003_department_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
    ]
